### PR TITLE
documentation and make sure things run fixes #98

### LINKED ISSUE #98: Verify that database install documentation is clear and that dev and prod database are easy to setup.
We need easy to install "sample/development" and "complete/prod" database installs. The project already more or less has these options and documentation of how to install each locally needs to be clear. 

This issue can be closed once both options have been installed, the process documented carefully,  and followup issues have been opened.

### PR DESCRIPTION
**Pull request by dblodgett-usgs**
This is mostly documentation but takes care of #98 -- I plan on taking care of #100 as a separate task.

### CODE REVIEW

**Review by gzt5142 — APPROVED** [review]
Successful clean-slate test on my WSL environment. 

`docker-compose up demo` raised a database that the crawler can connect to and fetch the table of crawler sources.

**Comment by dblodgett-usgs** [comment]
Going to go ahead and merge. If @webb-ben or @ewojtylko have input we can follow up seperately.

**Comment by ewojtylko** [comment]
Sorry for the lack of input.  My WSL/docker is out of whack and am waiting for some IT assistance but cannot test independently at the moment.

**Comment by dblodgett-usgs** [comment]
No worries -- regardless of you ability to run this stuff, is it tracking big picture? Anything we should put in to help better describe it for an uninitiated developer?

**Pull request merged**
